apps/index/urls.py
from django.urls import path
from .views import IndexView, CreatePedido, ShowPedidos, AddToCart,AsignarPedido, EntregarPedido, PedidoEntregado

app_name = 'index'

# These are the urls used in the project
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('crearPedido/', CreatePedido.as_view(), name='create'),
    path('verPedidos/', ShowPedidos.as_view(), name='show'),
    path('agregarCarrito/', AddToCart.as_view(), name='add'),
    path('asignarPedido/', AsignarPedido.as_view(), name='asignar'),
    path('entregarPedido/', EntregarPedido.as_view(), name='entregar'),
    path('pedidosEntregados/', PedidoEntregado.as_view(), name='entregados')
]

kovineats/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.index.urls'))
]

apps/index/templates/pedidos.html
<!DOCTYPE html>
{% load static %}
<html>
    <title>Kovin EATS</title>
    <link rel="icon" href="{% static 'images/icon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css"
    rel="stylesheet"
    />
    <!-- MDB -->
    <head>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
        
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <a class="navbar-brand mt-2 mt-lg-0" href="/">
                        <img
                            src="{% static 'images/logo.png' %}"
                            height="50"
                            alt="Kovin Eats Logo"
                            loading="lazy"
                        />
                    </a>
                </div>

                <div class="input-group d-flex justify-content-center">
                    <div class="form-outline" style="width:50%;">
                      <input type="search" id="form1" class="form-control" />
                      <label class="form-label" for="form1">Buscar Restaurantes | Platillos</label>
                    </div>
                    <button type="button" class="btn btn-primary">
                      <i class="fas fa-search"></i>
                    </button>
                </div>
        
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-primary" 
                        data-mdb-toggle="modal" data-mdb-toggle="modal" data-mdb-target="#modalCarrito">
                        <i class="fas fa-shopping-cart"></i>
                    </button>
                    <a type="button" href="{% url 'index:show' %}" class="btn btn-primary" aria-label="Ver pedidos"><i class="fas fa-receipt"></i></a>
                </div>
            </div>
        </nav>

        <div style="margin-top: 1%;margin-bottom: 1%;margin-left: 1%;margin-right: 1%;">
            <h1>Pedidos</h1>
        </div>

        <table class="table">
            <thead>
                <th>Folio</th>
                <th>Platillo</th>
                <th>Ingredientes</th>
                <th>Fecha del pedido</th>
                <th>Repartidor</th>
                <th>Método de pago</th>
                <th>Total</th>
                <th>Activo</th>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                    <tr>
                        <td>
                            <p>{{pedido.folio}}</p>
                        </td>
                        <td>
                            {% for platillo in pedido.platillos.all %}
                                <p>{{platillo.nombre}}</p>
                            {% endfor %}
                        </td>
                        <td>
                            {% for platillo in pedido.platillos.all %}
                                {% for ingrediente in platillo.ingredientes.all %}
                                <p>{{ingrediente.nombre}}</p>
                                {% endfor %}
                            {% endfor %}
                        </td>
                        <td>
                            <p>{{pedido.fecha_pedido}}</p>
                        </td>
                        <td>
                            <p>{{pedido.repartidor}}</p>
                        </td>
                        <td>
                            <p>Efectivo</p>
                        </td>
                        <td>
                            <p>{{pedido.total}}</p>
                        </td>
                        <td>
                            <div>
                                {%if pedido.activo%}
                                <i class="fas fa-check"></i>
                                {%else%}
                                <i class="fas fa-times"></i>
                                {%endif%}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <footer class="bg-light text-center text-lg-start">
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                <p style="color:black;display: inline;">
                    © 2022 Copyright Kovin
                    <p style="color: #1266f1;display:inline">EATS.</p>
                    <p>Made by Kevin Moreno Parra for Dagoberto's class.</p>
                </p> 
            </div>
            <!-- Copyright -->
        </footer> 

    </body>

</html>

apps/index/templates/pedidos_entregados.html
<!DOCTYPE html>
{% load static %}
<html>
    <title>Kovin EATS</title>
    <link rel="icon" href="{% static 'images/icon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    rel="stylesheet"
    />
    <!-- MDB -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css"
    rel="stylesheet"
    />
    <!-- MDB -->
    <head>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
        
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <a class="navbar-brand mt-2 mt-lg-0" href="/">
                        <img
                            src="{% static 'images/logo.png' %}"
                            height="50"
                            alt="Kovin Eats Logo"
                            loading="lazy"
                        />
                    </a>
                </div>

                <div class="input-group d-flex justify-content-center">
                    <div class="form-outline" style="width:50%;">
                      <input type="search" id="form1" class="form-control" />
                      <label class="form-label" for="form1">Buscar Restaurantes | Platillos</label>
                    </div>
                    <button type="button" class="btn btn-primary">
                      <i class="fas fa-search"></i>
                    </button>
                </div>
        
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-primary" 
                        data-mdb-toggle="modal" data-mdb-toggle="modal" data-mdb-target="#modalCarrito">
                        <i class="fas fa-shopping-cart"></i>
                    </button>
                    <a type="button" href="{% url 'index:show' %}" class="btn btn-primary" aria-label="Ver pedidos"><i class="fas fa-receipt"></i></a>
                </div>
            </div>
        </nav>

        <div style="margin-top: 1%;margin-bottom: 1%;margin-left: 1%;margin-right: 1%;">
            <h1>Pedidos entregados</h1>
        </div>

        <table class="table">
            <thead>
                <th>Folio</th>
                <th>Platillo</th>
                <th>Ingredientes</th>
                <th>Fecha del pedido</th>
                <th>Repartidor</th>
                <th>Método de pago</th>
                <th>Total</th>
                <th>Hora de entrega</th>
                <th>Tiempo de entrega</th>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                    <tr>
                        <td>
                            <p>{{pedido.folio}}</p>
                        </td>
                        <td>
                            {% for platillo in pedido.platillos.all %}
                                <p>{{platillo.nombre}}</p>
                            {% endfor %}
                        </td>
                        <td>
                            {% for platillo in pedido.platillos.all %}
                                {% for ingrediente in platillo.ingredientes.all %}
                                <p>{{ingrediente.nombre}}</p>
                                {% endfor %}
                            {% endfor %}
                        </td>
                        <td>
                            <p>{{pedido.fecha_pedido}}</p>
                        </td>
                        <td>
                            <p>{{pedido.repartidor}}</p>
                        </td>
                        <td>
                            <p>Efectivo</p>
                        </td>
                        <td>
                            <p>{{pedido.total}}</p>
                        </td>
                        <td>
                            <div>
                                {{pedido.hora_entrega}}
                            </div>
                        </td>
                        <td>
                            <div>
                                {{pedido.tiempo_entrega}}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <footer class="bg-light text-center text-lg-start">
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                <p style="color:black;display: inline;">
                    © 2022 Copyright Kovin
                    <p style="color: #1266f1;display:inline">EATS.</p>
                    <p>Made by Kevin Moreno Parra for Dagoberto's class.</p>
                </p> 
            </div>
            <!-- Copyright -->
        </footer> 

    </body>

</html>